/* soapRManagerProxy.cpp
   Generated by gSOAP 2.8.16 from RManager.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapRManagerProxy.h"

RManagerProxy::RManagerProxy()
{	RManagerProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

RManagerProxy::RManagerProxy(const struct soap &_soap) : soap(_soap)
{ }

RManagerProxy::RManagerProxy(const char *url)
{	RManagerProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

RManagerProxy::RManagerProxy(soap_mode iomode)
{	RManagerProxy_init(iomode, iomode);
}

RManagerProxy::RManagerProxy(const char *url, soap_mode iomode)
{	RManagerProxy_init(iomode, iomode);
	soap_endpoint = url;
}

RManagerProxy::RManagerProxy(soap_mode imode, soap_mode omode)
{	RManagerProxy_init(imode, omode);
}

RManagerProxy::~RManagerProxy()
{ }

void RManagerProxy::RManagerProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "urn:rm", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
}

void RManagerProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void RManagerProxy::reset()
{	destroy();
	soap_done(this);
	soap_initialize(this);
	RManagerProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void RManagerProxy::soap_noheader()
{	this->header = NULL;
}

const SOAP_ENV__Header *RManagerProxy::soap_header()
{	return this->header;
}

const SOAP_ENV__Fault *RManagerProxy::soap_fault()
{	return this->fault;
}

const char *RManagerProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *RManagerProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int RManagerProxy::soap_close_socket()
{	return soap_closesock(this);
}

int RManagerProxy::soap_force_close_socket()
{	return soap_force_closesock(this);
}

void RManagerProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void RManagerProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *RManagerProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int RManagerProxy::data(const char *endpoint, const char *soap_action, ns1__transport *req, ns1__transport &res)
{	struct soap *soap = this;
	struct ns1__data soap_tmp_ns1__data;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.0.0.2/cgi-bin/server.cgi";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__data.req = req;
	soap_serializeheader(soap);
	soap_serialize_ns1__data(soap, &soap_tmp_ns1__data);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__data(soap, &soap_tmp_ns1__data, "ns1:data", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__data(soap, &soap_tmp_ns1__data, "ns1:data", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&res)
		return soap_closesock(soap);
	res.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	res.soap_get(soap, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
